# Generated by Django 5.2.5 on 2026-01-27 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.DateField()),
                ('saldo', models.IntegerField(default=0)),
                ('cnae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.cnae')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='VinculosAtivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.DateField()),
                ('quantidade', models.IntegerField(default=0)),
                ('cnae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.cnae')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.municipio')),
            ],
        ),
    ]
