# Generated by Django 5.2.5 on 2026-01-14 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl', '0010_alter_estabelecimento_codigo_municipio_rf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoColetado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=50)),
                ('ano', models.IntegerField(default=0)),
                ('mes', models.IntegerField(default=0)),
                ('path_zip', models.TextField(blank=True, default='')),
                ('path_extraido', models.TextField(blank=True, default='')),
                ('path_filtrado', models.TextField(blank=True, default='')),
                ('bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('DOWNLOADED', 'Baixado'), ('EXTRACTED', 'Extraído'), ('FILTERED', 'Filtrado'), ('LOADED', 'Carregado'), ('FAILED', 'Falhou')], default='PENDING', max_length=10)),
                ('linhas_filtradas', models.BigIntegerField(default=0)),
                ('msg', models.TextField(blank=True, default='')),
                ('expected_bytes', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='vinculos_ativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subclasse_cnae', models.CharField(max_length=7)),
                ('data', models.DateField()),
                ('quantidade', models.IntegerField(default=0)),
                ('cnae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.cnae', to_field='codigo')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.municipio')),
            ],
        ),
    ]
