# Generated by Django 5.2.5 on 2026-02-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('rais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinculosativos',
            options={'verbose_name': 'Vínculo Ativo', 'verbose_name_plural': 'Vínculos Ativos'},
        ),
        migrations.AddIndex(
            model_name='saldo',
            index=models.Index(fields=['municipio', 'cnae', 'referencia'], name='rais_saldo_municip_96bd4c_idx'),
        ),
        migrations.AddIndex(
            model_name='vinculosativos',
            index=models.Index(fields=['municipio', 'cnae', 'referencia'], name='rais_vincul_municip_33acfe_idx'),
        ),
    ]
