# Generated by Django 5.2.5 on 2026-01-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0010_alter_estabelecimento_codigo_municipio_rf'),
        ('rais', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vinculos_ativos',
            new_name='VinculosAtivos',
        ),
    ]
