# Generated by Django 5.2.5 on 2026-02-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('rais', '0002_alter_vinculosativos_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VinculosAtivos',
            new_name='EstoqueAnual',
        ),
        migrations.RenameIndex(
            model_name='estoqueanual',
            new_name='rais_estoqu_municip_b76d37_idx',
            old_name='rais_vincul_municip_33acfe_idx',
        ),
        migrations.AddIndex(
            model_name='estoqueanual',
            index=models.Index(fields=['municipio', 'cnae'], name='rais_estoqu_municip_1b6218_idx'),
        ),
    ]
