# Generated by Django 5.2.5 on 2026-01-15 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('rais', '0002_rename_vinculos_ativos_vinculosativos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArquivoColetado',
        ),
        migrations.AlterField(
            model_name='vinculosativos',
            name='cnae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.cnae', to_field='codigo'),
        ),
        migrations.AlterField(
            model_name='vinculosativos',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.municipio'),
        ),
    ]
