# Generated by Django 5.2.5 on 2026-02-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('rais', '0003_rename_vinculosativos_estoqueanual_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saldo',
            new_name='SaldoMensal',
        ),
        migrations.AlterModelOptions(
            name='estoqueanual',
            options={'verbose_name': 'Estoque Anual', 'verbose_name_plural': 'Estoques Anuais'},
        ),
        migrations.RenameIndex(
            model_name='saldomensal',
            new_name='rais_saldom_municip_5b87b5_idx',
            old_name='rais_saldo_municip_96bd4c_idx',
        ),
    ]
