# Generated by Django 5.2.5 on 2026-02-14 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('rais', '0004_rename_saldo_saldomensal_alter_estoqueanual_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saldomensal',
            options={'verbose_name': 'Saldo Mensal', 'verbose_name_plural': 'Saldos Mensais'},
        ),
        migrations.RenameField(
            model_name='estoqueanual',
            old_name='quantidade',
            new_name='estoque',
        ),
        migrations.CreateModel(
            name='EstoqueMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.DateField()),
                ('estoque', models.IntegerField(default=0)),
                ('cnae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.cnae')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.municipio')),
            ],
            options={
                'verbose_name': 'Estoque Mensal',
                'verbose_name_plural': 'Estoques Mensais',
                'indexes': [models.Index(fields=['municipio', 'cnae', 'referencia'], name='rais_estoqu_municip_c5defc_idx')],
            },
        ),
    ]
