# Generated by Django 5.2.5 on 2026-02-04 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAGED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refencia', models.DateField()),
                ('saldo_caged', models.IntegerField()),
                ('cnae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.cnae')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.municipio')),
            ],
            options={
                'indexes': [models.Index(fields=['municipio', 'cnae', 'refencia'], name='caged_caged_municip_8a5c0e_idx')],
                'unique_together': {('municipio', 'cnae', 'refencia')},
            },
        ),
    ]
