# Generated by Django 5.2.5 on 2026-02-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('caged', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='caged',
            name='caged_caged_municip_8a5c0e_idx',
        ),
        migrations.RenameField(
            model_name='caged',
            old_name='refencia',
            new_name='referencia',
        ),
        migrations.AlterUniqueTogether(
            name='caged',
            unique_together={('municipio', 'cnae', 'referencia')},
        ),
        migrations.AddIndex(
            model_name='caged',
            index=models.Index(fields=['municipio', 'cnae', 'referencia'], name='caged_caged_municip_be79fa_idx'),
        ),
    ]
