# Generated by Django 5.2.5 on 2026-02-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caged', '0002_remove_caged_caged_caged_municip_8a5c0e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caged',
            name='saldo_caged',
            field=models.IntegerField(default=0),
        ),
    ]
