# Generated by Django 5.2.5 on 2026-02-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('caged', '0003_alter_caged_saldo_caged'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CAGED',
            new_name='SaldoMensalCaged',
        ),
        migrations.AlterModelOptions(
            name='saldomensalcaged',
            options={'verbose_name': 'Saldo Mensal Caged', 'verbose_name_plural': 'Saldos Mensais Caged'},
        ),
        migrations.RenameIndex(
            model_name='saldomensalcaged',
            new_name='caged_saldo_municip_9a9736_idx',
            old_name='caged_caged_municip_be79fa_idx',
        ),
    ]
