# Generated by Django 5.2.5 on 2026-01-27 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('cnpj_completo', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('cnpj_basico', models.CharField(max_length=8)),
                ('cnpj_ordem', models.CharField(max_length=4)),
                ('cnpj_dv', models.CharField(max_length=2)),
                ('identidade_matriz_ou_filial', models.SmallIntegerField()),
                ('nome_fantasia', models.TextField(blank=True, null=True)),
                ('situacao_cadastral', models.CharField(max_length=2)),
                ('data_situacao_cadastral', models.DateField(blank=True, null=True)),
                ('motivo_situacao_cadastral', models.SmallIntegerField(blank=True, null=True)),
                ('nome_cidade_exterior', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_pais', models.CharField(blank=True, max_length=10, null=True)),
                ('data_inicio_atividade', models.DateField(blank=True, null=True)),
                ('cnae_fiscal_principal', models.CharField(max_length=7)),
                ('cnae_fiscal_secundaria', models.TextField(blank=True, null=True)),
                ('tipo_logradouro', models.CharField(blank=True, max_length=30, null=True)),
                ('logradouro', models.TextField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.TextField(blank=True, null=True)),
                ('bairro', models.TextField(blank=True, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('dd1', models.CharField(blank=True, max_length=3, null=True)),
                ('telefone1', models.CharField(blank=True, max_length=15, null=True)),
                ('ddd2', models.CharField(blank=True, max_length=3, null=True)),
                ('telefone2', models.CharField(blank=True, max_length=15, null=True)),
                ('dddfax', models.CharField(blank=True, max_length=3, null=True)),
                ('fax', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('situacao_especial', models.TextField(blank=True, null=True)),
                ('data_situacao_especial', models.DateField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('classe_cnae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.cnae')),
                ('codigo_municipio_rf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimentos_ibge', to='cadastros.municipio', to_field='codigo_receita_federal')),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
                'indexes': [models.Index(fields=['data_atualizacao'], name='receita_fed_data_at_d40985_idx'), models.Index(fields=['codigo_municipio_rf'], name='receita_fed_codigo__04e3f1_idx'), models.Index(fields=['cnpj_basico', 'cnpj_ordem', 'cnpj_dv'], name='receita_fed_cnpj_ba_87e7b1_idx')],
            },
        ),
    ]
