# Generated by Django 5.2.5 on 2026-01-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CNAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('descricao', models.TextField()),
                ('classificacao_otmg', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo_ibge', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('codigo_receita_federal', models.PositiveBigIntegerField(default=0, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('uf', models.CharField(default='MG', max_length=2)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municípios',
            },
        ),
    ]
