# Generated by Django 5.2.5 on 2025-11-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoColetado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=50)),
                ('path', models.TextField(blank=True, default='')),
                ('bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('DOWNLOADED', 'Baixado'), ('EXTRACTED', 'Extraído'), ('FILTERED', 'Filtrado'), ('LOADED', 'Carregado'), ('FAILED', 'Falhou')], default='PENDING', max_length=10)),
                ('linhas_filtradas', models.BigIntegerField(default=0)),
                ('msg', models.TextField(blank=True, default='')),
                ('expected_bytes', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
