# Generated by Django 5.2.5 on 2025-11-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivocoletado',
            name='ano',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arquivocoletado',
            name='mes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
