# Generated by Django 5.2.5 on 2025-11-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_arquivocoletado_ano_arquivocoletado_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivocoletado',
            name='ano',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arquivocoletado',
            name='mes',
            field=models.IntegerField(default=0),
        ),
    ]
