# Generated by Django 5.2.5 on 2025-11-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_alter_arquivocoletado_ano_alter_arquivocoletado_mes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquivocoletado',
            old_name='path',
            new_name='path_extraido',
        ),
        migrations.AddField(
            model_name='arquivocoletado',
            name='path_filtrado',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='arquivocoletado',
            name='path_zip',
            field=models.TextField(blank=True, default=''),
        ),
    ]
