# Generated by Django 5.2.5 on 2025-12-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_rename_path_arquivocoletado_path_extraido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipioAlvo',
            fields=[
                ('codigo_ibge', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('codigo_receita_federal', models.PositiveBigIntegerField(default=0, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('uf', models.CharField(default='MG', max_length=2)),
            ],
            options={
                'verbose_name': 'Município Alvo',
                'verbose_name_plural': 'Municípios Alvo',
            },
        ),
    ]
