# Generated by Django 5.2.5 on 2025-12-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_municipioalvo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MunicipioAlvo',
            new_name='Municipio',
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name': 'Municipio', 'verbose_name_plural': 'Municípios'},
        ),
    ]
