# Generated by Django 5.2.5 on 2025-12-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_rename_municipioalvo_municipio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('descricao', models.TextField()),
                ('classificacao_otmg', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
    ]
