# Generated by Django 5.2.5 on 2025-12-16 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0007_cnae'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('cnpj_completo', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('cnpj_basico', models.CharField(max_length=8)),
                ('cnpj_ordem', models.CharField(max_length=4)),
                ('cnpj_dv', models.CharField(max_length=2)),
                ('identidade_matriz_ou_filial', models.SmallIntegerField()),
                ('nome_fantasia', models.TextField(blank=True, null=True)),
                ('situacao_cadastral', models.SmallIntegerField()),
                ('data_situacao_cadastral', models.DateField(blank=True, null=True)),
                ('motivo_situacao_cadastral', models.SmallIntegerField(blank=True, null=True)),
                ('nome_cidade_exterior', models.TextField(blank=True, null=True)),
                ('codigo_pais', models.TextField(blank=True, null=True)),
                ('data_inicio_atividade', models.DateField(blank=True, null=True)),
                ('cnae_fiscal_principal', models.CharField(max_length=7)),
                ('cnae_fiscal_secundaria', models.TextField(blank=True, null=True)),
                ('tipo_logradouro', models.TextField(blank=True, null=True)),
                ('logradouro', models.TextField(blank=True, null=True)),
                ('numero', models.TextField(blank=True, null=True)),
                ('complemento', models.TextField(blank=True, null=True)),
                ('bairro', models.TextField(blank=True, null=True)),
                ('cep', models.TextField(blank=True, null=True)),
                ('uf', models.TextField(blank=True, null=True)),
                ('dd1', models.SmallIntegerField(blank=True, null=True)),
                ('telefone1', models.TextField(blank=True, null=True)),
                ('ddd2', models.CharField(blank=True, max_length=5, null=True)),
                ('telefone2', models.TextField(blank=True, null=True)),
                ('dddfax', models.TextField(blank=True, null=True)),
                ('fax', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('situacao_especial', models.TextField(blank=True, null=True)),
                ('data_situacao_especial', models.DateField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('classe_cnae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.cnae', to_field='codigo')),
                ('codigo_municipio_rf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimentos_ibge', to='etl.municipio')),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
                'indexes': [models.Index(fields=['data_atualizacao'], name='etl_estabel_data_at_a64827_idx'), models.Index(fields=['codigo_municipio_rf'], name='etl_estabel_codigo__ca9791_idx'), models.Index(fields=['cnpj_basico', 'cnpj_ordem', 'cnpj_dv'], name='etl_estabel_cnpj_ba_90d644_idx')],
            },
        ),
    ]
