# Generated by Django 5.2.5 on 2026-01-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0008_estabelecimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='codigo_pais',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='dd1',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='ddd2',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='dddfax',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='fax',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='nome_cidade_exterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='situacao_cadastral',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='telefone1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='telefone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='tipo_logradouro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
