# Generated by Django 5.2.5 on 2026-01-06 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0009_alter_estabelecimento_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='codigo_municipio_rf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimentos_ibge', to='etl.municipio', to_field='codigo_receita_federal'),
        ),
    ]
