# Generated by Django 5.2.5 on 2026-01-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0010_alter_estabelecimento_codigo_municipio_rf'),
        ('rais', '0003_delete_arquivocoletado_alter_vinculosativos_cnae_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='classe_cnae',
        ),
        migrations.RemoveField(
            model_name='estabelecimento',
            name='codigo_municipio_rf',
        ),
        migrations.DeleteModel(
            name='CNAE',
        ),
        migrations.DeleteModel(
            name='Estabelecimento',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
